repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # Add new projects by copying the block below and creating a new values file
  - name: example-project-redis-exporter
    chart: prometheus-community/prometheus-redis-exporter
    namespace: monitoring
    version: 6.22.0
    values:
      - values/example-project.yaml
