apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: prometheus-backend-config
  namespace: prometheus
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /-/healthy
    port: 9090
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: prometheus-frontend-config
  namespace: prometheus
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-server-ingress
  namespace: prometheus
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "somaz-gke-prometheus-lb-ip"
    networking.gke.io/managed-certificates: "prometheus-certificate"
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: prometheus-frontend-config
spec:
  rules:
  - host: prometheus.somaz.link
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prometheus-server
            port:
              number: 80
