repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: promtail
    namespace: monitoring
    chart: grafana/promtail
    version: 6.16.5
    values:
      - values/somaz-onpremise.yaml
