repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: dandydeveloper
    url: https://dandydeveloper.github.io/charts/

releases:
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: 9.5.4
    values:
      - values/mgmt.yaml               # global, configs (cm/params/ssh/rbac/secrets)
      - values/mgmt-server.yaml        # controller, dex, server, repoServer, applicationSet
      - values/mgmt-redis.yaml         # redis, redis-ha, redisSecretInit
      - values/mgmt-notifications.yaml # notifications controller (Slack templates/triggers)

# helmDefaults:
#   wait: true
#   timeout: 600
#   atomic: true
#   cleanupOnFail: true

# Hooks to ensure proper installation and upgrades
hooks:
  - events: ["presync"]
    showlogs: true
    command: "helm"
    args:
      - "dependency"
      - "update"
      - "."

  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "create"
      - "namespace"
      - "argocd"
      - "--dry-run=client"
      - "-o"
      - "yaml"
      - "||"
      - "true" 