apiVersion: v2
name: kube-prometheus-stack
description: Prometheus monitoring stack for Kubernetes (Prometheus, Grafana, Alertmanager, node-exporter, kube-state-metrics)
type: application
version: 82.18.0
appVersion: "v0.89.0"
home: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
maintainers:
  - name: prometheus-community
    url: https://github.com/prometheus-community
