repositories:
  - name: elastic
    url: https://helm.elastic.co

releases:
  - name: elasticsearch
    namespace: monitoring
    chart: .
    version: 8.5.1
    values:
      - values/mgmt.yaml

# Hooks to ensure proper installation and upgrades
hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "create"
      - "namespace"
      - "monitoring"
      - "--dry-run=client"
      - "-o"
      - "yaml"
      - "||"
      - "true"
