stages:
  - build # buld images & push to private image registry at once
  - update

variables:
  NAMESPACE:
    value: "dev1"
    description: "Select the namespace: dev1 or dev2 or etc"
  SERVICE:
    value: "admin"
    description: "Select admin or etc"

  IMAGE_PROJECT: souls
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$IMAGE_PROJECT/$SERVICE
  BUILD_TAG: $CI_COMMIT_SHORT_SHA
  BUILD_TAG_LATEST: latest
  IMAGE_URL_LATEST: $CI_REGISTRY_IMAGE:$BUILD_TAG_LATEST
  IMAGE_URL: $CI_REGISTRY_IMAGE:$BUILD_TAG

.templates:
  .common_build_before_script: &common_build_before_script
    - echo "[INFO] Start build image."
    - echo "[INFO] CI_REGISTRY is $CI_REGISTRY"
    - echo "[INFO] CI_REGISTRY_IMAGE is $CI_REGISTRY_IMAGE"
    - echo "[INFO] BUILD_TAG is $BUILD_TAG"
    - echo "[INFO] IMAGE_URL is $IMAGE_URL"
    - echo "[INFO] SERVICE is $SERVICE"
    - echo "[INFO] NAMESPACE is $NAMESPACE"
    - mkdir -p /kaniko/.docker
    - >
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json

  .common_build_script: &common_build_script
    - >      
      /kaniko/executor 
      --cache=true 
      --cache-ttl=24h 
      --snapshot-mode=redo 
      --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/Dockerfile 
      --destination $CI_REGISTRY_IMAGE:$BUILD_TAG 
      --destination $CI_REGISTRY_IMAGE:$BUILD_TAG_LATEST 
      --build-arg NODE_ENV=$NAMESPACE 
      --insecure 
      --insecure-pull

  .common_update_before_script: &common_update_before_script
    - echo "[INFO] BUILD_TAG is $BUILD_TAG"
    - echo "[INFO] SERVICE is $SERVICE"
    - echo "[INFO] NAMESPACE is $NAMESPACE"
    - apk add --no-cache sed git openssh
    - eval $(ssh-agent -s)
    - echo "$GITLAB_SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh 
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\nUserKnownHostsFile=/dev/null" > ~/.ssh/config
    - export GITLAB_SSH_KNOWN_HOSTS=$(ssh-keyscan gitlab.example.com)
    - echo "$GITLAB_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

  .common_update_script: &common_update_script
    - git clone git@gitlab.example.com:group/argocd-applicationset.git
    - cd argocd-applicationset
    - git checkout master
    - cd values/$IMAGE_PROJECT/$SERVICE
    - 'sed -i "s/tag: \".*\"/tag: \"$BUILD_TAG\"/" $NAMESPACE.values.yaml'
    - git add .
    - if git diff --cached --quiet; then echo "No changes to commit"; else
        git config --global user.email "cicd@example.com";
        git config --global user.name "cicd";
        git commit -m "Update image $NAMESPACE-$IMAGE_PROJECT-$SERVICE tag to $BUILD_TAG";
        git push origin master;
      fi

.change_files: &change_files
  changes:
    - Function/**/*
    - .idea/**/*
    - Dockerfile
    - node_modules/**/*
    - config/*
    - index.js
    - package-lock.json
    - package.json
    # - .gitlab-ci.yml

build_manual_image:
  stage: build
  image:
    name: registry.example.com/library/kaniko-project/executor:v1.23.0-debug
  interruptible: true
  retry:
    max: 2  # Maximum of 2 retries
    when:
      - runner_system_failure
      - unknown_failure
      - data_integrity_failure
  before_script: *common_build_before_script
  script: *common_build_script
  rules:
    - if: '($CI_PIPELINE_SOURCE == "web")'
  tags:
    - build-deploy-image

build_auto_image:
  stage: build
  image:
    name: registry.example.com/library/kaniko-project/executor:v1.23.0-debug
  interruptible: true
  retry:
    max: 2  # Maximum of 2 retries
    when:
      - runner_system_failure
      - unknown_failure
      - data_integrity_failure
  before_script: *common_build_before_script
  script: *common_build_script
  rules:
    # Trigger this job only when files other than .gitlab-ci.yml are changed
    # - changes:
    #   - "**/*"  # Matches all files
    # - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      <<: *change_files
  tags:
    - build-deploy-image

update_manual_image:
  stage: update
  image: registry.example.com/library/alpine:latest
  interruptible: true
  retry:
    max: 2  # Maximum of 2 retries
    when:
      - runner_system_failure
      - unknown_failure
      - data_integrity_failure
  before_script: *common_update_before_script
  script: *common_update_script 
  # after_script: *common_update_after_script
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  tags:
    - build-deploy-image

update_auto_image:
  stage: update
  image: registry.example.com/library/alpine:latest
  interruptible: true
  retry:
    max: 2  # Maximum of 2 retries
    when:
      - runner_system_failure
      - unknown_failure
      - data_integrity_failure
  before_script: *common_update_before_script
  script: *common_update_script 
  # after_script: *common_update_after_script
  rules:
    # Trigger this job only when files other than .gitlab-ci.yml are changed
    # - changes:
    #   - "**/*"  # Matches all files
    # - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      <<: *change_files
  tags:
    - build-deploy-image
