apiVersion: v2
name: thanos
description: Thanos - highly available Prometheus setup with long-term storage
type: application
version: 16.5.0
appVersion: "0.37.2"
home: https://thanos.io
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/thanos
  - https://github.com/thanos-io/thanos
maintainers:
  - name: bitnami
    url: https://github.com/bitnami
