repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # Thanos Sidecar components (compactor, store gateway, object storage)
  - name: thanos
    chart: bitnami/thanos
    namespace: monitoring
    version: 17.3.1
    values:
      - values/mgmt.yaml

  # Thanos Query (separate instance for unified query across clusters)
  - name: thanos-query
    chart: bitnami/thanos
    namespace: monitoring
    version: 17.3.1
    values:
      - values/mgmt-query.yaml
