repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: monitoring
    chart: .
    version: 8.5.1
    values:
      - values/somaz-onpremise.yaml
