quiet: true
skip-check:
  # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_2
  # Ensure that a user for the container has been created
  - CKV_DOCKER_3
  - CKV_GHA_7
  - CKV_K8S_*
  - CKV2_K8S_*  
