# .golangci.yml
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - goanalysis_metalinter

issues:
  exclude-rules:
    - path: "github.com/prometheus/client_golang/api"
      text: "no export data for"
      linters:
        - goanalysis_metalinter

  # General exclude patterns can also be defined
  exclude:
    - "could not load export data: no export data for"
