apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: ingress-nginx
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name tail
        Path /var/log/nginx/access.log
        Parser nginx_access_parser
        Tag nginx_access

    [INPUT]
        Name tail
        Path /var/log/nginx/error.log
        Parser nginx_error_parser
        Tag nginx_error

    [FILTER]
        Name    grep
        Match   nginx_access
        Regex   log .*somaz.*

    [FILTER]
        Name    modify
        Match   nginx_access
        Add     log_type nginx_access

    [FILTER]
        Name    modify
        Match   nginx_error
        Add     log_type nginx_error

    [OUTPUT]
        Name stdout
        Match *

    [OUTPUT]
        Name loki
        Match *
        Host loki.somaz.link
        Port 443
        URI /loki/api/v1/push
        tls On
        Labels job=fluent-bit, log_type=$log_type

  parsers.conf: |
    [PARSER]
        Name        nginx_access_parser
        Format      regex
        Regex       ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+) (?<request>[^ ]*) (?<http_protocol>[^"]*)" (?<status>[^ ]*) (?<body_bytes_sent>[^ ]*) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<upstream_name>[^\]]*)\] \[(?<upstream_addr>[^\]]*)\] (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<request_id>[^ ]*)$
        Time_Key    time
        Time_Format  %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        nginx_error_parser
        Format      regex
        Regex       ^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<log_level>\w+)\] (?<process_info>\d+#\d+): (?<message>.*)$
        Time_Key    time
        Time_Format  %Y/%m/%d %H:%M:%S
