## Redis
redis:
  enabled: true

## Redis-HA subchart replaces custom redis deployment when `redis-ha.enabled=true`
# Ref: https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/values.yaml
redis-ha:
  enabled: false

redisSecretInit:
  enabled: true

