apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: eh-jenkins
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/jenkins
    server: nfs-server.somaz.link

