stages:
  - upload_data_server
  - upload_data_client

variables:
  STAGES:
    value: "upload_data_server"
    description: "Select the stages: upload_data_server or upload_data_client(use web)"
    options:
      - "upload_data_server"
      - "upload_data_client"

.change_files_server: &change_files_server
  changes:
    - somaz/data/**/*
    - somaz/SomazServerJson/*

upload_data_server:
  stage: upload_data_server
  image: alpine:latest

  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "${NFS_SSH_PRIVATE_KEY}"
    - echo "${NFS_SSH_PRIVATE_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\nUserKnownHostsFile=/dev/null" > ~/.ssh/config
  script:
    - rsync -avzr --delete --progress Somaz/SomazJson/* somaz@nfs-server.somaz.link:/data/somaz/somazdata/$CI_COMMIT_REF_NAME/
  artifacts:
    paths:
      - somaz/SomazServerJson/*
    expire_in: 1 days
  after_script:
    - apk add curl
    - apk add git
    - CHANGED_SomazServerjson=$(git diff --name-only HEAD~1 HEAD | grep SomazServerJson | grep -E '\.json$' | awk -F/ '{print $NF}' | awk -F. '{print $1}')
    - "curl -X POST -F token=${GAMESERVER_TRIGGER_TOKEN} -F ref=${CI_COMMIT_REF_NAME} -F variables[project_id]=${CI_PROJECT_ID} -F variables[changed_SomazServerJson]=\"${CHANGED_SomazServerJson}\" -F variables[job_id]=${CI_JOB_ID}  http://gitlab.somaz.link/api/v4/projects/74/trigger/pipeline"
  tags:
    - build-somaz-image
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == "dev1")'
      <<: *change_files_server
    - if: '$CI_PIPELINE_SOURCE == "web" && ($CI_COMMIT_REF_NAME == "dev1") && $STAGES == "upload_data_server"'


.change_files_client: &change_files_client
  changes:
    - Convertor/SomazlientJson/*

upload_data_client:
  stage: upload_data_client
  image:
    name: python:3.8-slim
    entrypoint: [""]
  variables:
    GCS_DESTINATION_PREFIX: "gamedata/${CI_COMMIT_REF_NAME}/latest"
  before_script:
    - pip install google-cloud-storage
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
    - ls -la
    - chmod +x script/sync_to_gcs_py
  script:
    - python script/sync_to_gcs_py $GCS_BUCKET_NAME $GCS_DESTINATION_PREFIX
  artifacts:
    paths:
      - Convertor/SomazClientJson/*
    expire_in: 1 days
  tags:
    - build-image
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == "dev1")'
      <<: *change_files_client
    - if: '$CI_PIPELINE_SOURCE == "web" && ($CI_COMMIT_REF_NAME == "dev1") && $STAGES == "upload_data_client"'

