stages:
  - upload_data

.change_files: &change_files
  changes:
    - somaz/data/**/*
    - somaz/SomazJson/*

upload_data:
  stage: upload_data
  image: alpine:latest

  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "${NFS_SSH_PRIVATE_KEY}"
    - echo "${NFS_SSH_PRIVATE_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\nUserKnownHostsFile=/dev/null" > ~/.ssh/config
  script:
    - rsync -avzr --delete --progress Somaz/SomazJson/* somaz@nfs-server.somaz.link:/data/somaz/somazdata/$CI_COMMIT_REF_NAME/
  artifacts:
    paths:
      - somaz/SomazJson/*
    expire_in: 1 days
  after_script:
    - apk add curl
    - apk add git
    - CHANGED_Somazjson=$(git diff --name-only HEAD~1 HEAD | grep SomazJson | grep -E '\.json$' | awk -F/ '{print $NF}' | awk -F. '{print $1}')
    - "curl -X POST -F token=${GAMESERVER_TRIGGER_TOKEN} -F ref=${CI_COMMIT_REF_NAME} -F variables[project_id]=${CI_PROJECT_ID} -F variables[changed_SomazJson]=\"${CHANGED_SomazJson}\" -F variables[job_id]=${CI_JOB_ID}  http://gitlab.somaz.link/api/v4/projects/74/trigger/pipeline"
  tags:
    - build-somaz-image
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      <<: *change_files
    - if: '$CI_PIPELINE_SOURCE == "web"'


