apiVersion: v1
kind: Secret
metadata:
  name: example-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:example-org/example-repo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Replace with your SSH private key registered in GitHub
    # Generate with: ssh-keygen -t ed25519 -f ~/.ssh/argocd-repo-key -C "argocd"
    -----END OPENSSH PRIVATE KEY-----
