{{- if and .Values.httproute.enabled .Values.httproute.backendTLS.enabled }}
{{- $secretName := printf "%s-es-http-certs-public" .Values.name }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if $secret }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    elasticsearch.k8s.elastic.co/source-secret: {{ $secretName }}
data:
  ca.crt: |
{{ index $secret.data "ca.crt" | b64dec | indent 4 }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ .Values.name }}-es-http
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: {{ .Values.name }}-ca
    hostname: {{ .Values.name }}-es-http
{{- end }}
{{- end }}
