{{- if .Values.elasticPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-es-elastic-user
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  elastic: {{ .Values.elasticPassword | quote }}
{{- end }}
