repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: monitoring
    createNamespace: true
    chart: grafana/grafana
    version: 10.5.15
    values:
      - values/mgmt.yaml

# Hooks to ensure proper installation and upgrades
hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "create"
      - "namespace"
      - "monitoring"
      - "--dry-run=client"
      - "-o"
      - "yaml"
      - "||"
      - "true"
