repositories:
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: build-image
    namespace: gitlab-runner
    createNamespace: true
    chart: gitlab/gitlab-runner
    version: 0.87.0
    values:
      - values/build.yaml

# Hooks to ensure proper installation and upgrades
hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "create"
      - "namespace"
      - "gitlab-runner"
      - "--dry-run=client"
      - "-o"
      - "yaml"
      - "||"
      - "true"