apiVersion: v1
kind: PersistentVolume
metadata:
  name: fs-pv-shared-vpc-grafana
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fs-sc-shared-vpc
  nfs:
    path: /vol1
    server: <filestore-ip>


