apiVersion: v1
kind: PersistentVolume
metadata:
  name: pd-pv-grafana
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pd-sc
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeHandle: <Persistent Disk Name> # The name of the Google Persistent Disk  
