# nfs-server
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-loki
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: nfs
  storageClassName: nfs-client
  nfs:
    path: /nfs/loki
    server: <nfs-server-ip>

