repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    chart: .
    version: 7.7.0
    values:
      - values/mgmt-single.yaml

  # HA mode
  # - name: argocd
  #   namespace: argocd
  #   chart: .
  #   version: 7.7.0
  #   values:
  #     - values/mgmt-ha.yaml

  # TLS single mode
  # - name: argocd
  #   namespace: argocd
  #   chart: .
  #   version: 7.7.0
  #   values:
  #     - values/mgmt-tls-single.yaml

  # TLS HA mode
  # - name: argocd
  #   namespace: argocd
  #   chart: .
  #   version: 7.7.0
  #   values:
  #     - values/mgmt-tls-ha.yaml
