---
# EFS StorageClass
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
---
# EFS PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-grafana
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0xxxxxxxxxxxxxxxxxxxx  # Replace with your EFS file system ID
