repositories:
  - name: elastic
    url: https://helm.elastic.co

releases:
  - name: elasticsearch
    namespace: elastic-system
    chart: elasticsearch
    version: 8.5.1
    values:
      - elasticsearch/values/mgmt.yaml

  - name: kibana
    namespace: elastic-system
    chart: kibana
    version: 8.5.1
    values:
      - kibana/values/mgmt.yaml

  - name: filebeat
    namespace: elastic-system
    chart: filebeat
    version: 8.5.1
    values:
      - filebeat/values/mgmt.yaml

  - name: logstash
    namespace: elastic-system
    chart: logstash
    version: 8.5.1
    values:
      - logstash/values/mgmt.yaml

  - name: apm-server
    namespace: elastic-system
    chart: apm-server
    version: 8.5.1
    values:
      - apm-server/values/mgmt.yaml

  - name: metricbeat
    namespace: elastic-system
    chart: metricbeat
    version: 8.5.1
    values:
      - metricbeat/values/mgmt.yaml
